# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 05:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('qr_code_text', models.CharField(max_length=200)),
                ('qr_code_img', models.ImageField(upload_to=b'/media/tenant/')),
                ('qr_code_url_text', models.URLField(blank=True, null=True)),
                ('qr_code_url_img', models.ImageField(blank=True, null=True, upload_to=b'/media/tenant/')),
                ('standard', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=10)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('updated_date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('qr_code_text', models.CharField(max_length=200)),
                ('qr_code_img', models.ImageField(upload_to=b'/media/tenant/')),
                ('qr_code_url_text', models.URLField(blank=True, null=True)),
                ('qr_code_url_img', models.ImageField(blank=True, null=True, upload_to=b'/media/tenant/')),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('start_month', models.CharField(max_length=3)),
                ('end_month', models.CharField(max_length=3)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('updated_date_time', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acd_year_crd_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acd_year_upd_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('qr_code_text', models.CharField(max_length=200)),
                ('qr_code_img', models.ImageField(upload_to=b'/media/tenant/')),
                ('qr_code_url_text', models.URLField(blank=True, null=True)),
                ('qr_code_url_img', models.ImageField(blank=True, null=True, upload_to=b'/media/tenant/')),
                ('established_year', models.IntegerField()),
                ('logo', models.ImageField(upload_to=b'')),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('updated_date_time', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sch_crd_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sch_perf_upd_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolAdministration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('qr_code_text', models.CharField(max_length=200)),
                ('qr_code_img', models.ImageField(upload_to=b'/media/tenant/')),
                ('qr_code_url_text', models.URLField(blank=True, null=True)),
                ('qr_code_url_img', models.ImageField(blank=True, null=True, upload_to=b'/media/tenant/')),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('updated_date_time', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sch_adm_crd_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sch_adm_upd_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mongo_id', models.CharField(max_length=100)),
                ('document_type', models.CharField(max_length=10)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('updated_date_time', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sch_doc_crd_by', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sch_doc_upd_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='academicclass',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.AcademicYear'),
        ),
        migrations.AddField(
            model_name='academicclass',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acd_cls_crd_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicclass',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acd_cls_upd_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
