# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 05:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicClassStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('qr_code_text', models.CharField(max_length=200)),
                ('qr_code_img', models.ImageField(upload_to=b'/media/tenant/')),
                ('qr_code_url_text', models.URLField(blank=True, null=True)),
                ('qr_code_url_img', models.ImageField(blank=True, null=True, upload_to=b'/media/tenant/')),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('updated_date_time', models.DateTimeField(auto_now_add=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.AcademicClass')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acd_cls_stud_crd_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('qr_code_text', models.CharField(max_length=200)),
                ('qr_code_img', models.ImageField(upload_to=b'/media/tenant/')),
                ('qr_code_url_text', models.URLField(blank=True, null=True)),
                ('qr_code_url_img', models.ImageField(blank=True, null=True, upload_to=b'/media/tenant/')),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('updated_date_time', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stud_crd_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stud_upd_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mongo_id', models.CharField(max_length=100)),
                ('document_type', models.CharField(max_length=10)),
                ('academic_class_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.AcademicClassStudent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('updated_date_time', models.DateTimeField(auto_now_add=True)),
                ('academic_class_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.AcademicClassStudent')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stud_subscr_crd_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stud_subscr_upd_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentTermPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('qr_code_text', models.CharField(max_length=200)),
                ('qr_code_img', models.ImageField(upload_to=b'/media/tenant/')),
                ('qr_code_url_text', models.URLField(blank=True, null=True)),
                ('qr_code_url_img', models.ImageField(blank=True, null=True, upload_to=b'/media/tenant/')),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('updated_date_time', models.DateTimeField(auto_now_add=True)),
                ('academic_class_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.AcademicClassStudent')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_perf_crd_by', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Term')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_perf_upd_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentTermSubjectPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('qr_code_text', models.CharField(max_length=200)),
                ('qr_code_img', models.ImageField(upload_to=b'/media/tenant/')),
                ('qr_code_url_text', models.URLField(blank=True, null=True)),
                ('qr_code_url_img', models.ImageField(blank=True, null=True, upload_to=b'/media/tenant/')),
                ('marks', models.DecimalField(decimal_places=3, max_digits=3)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('updated_date_time', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_sub_perf_crd_by', to=settings.AUTH_USER_MODEL)),
                ('student_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentTermPerformance')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Subject')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_sub_perf_upd_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='academicclassstudent',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='academicclassstudent',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acd_cls_stud_upd_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
