doc-warnings: true
test-warnings: true
strictness: veryhigh
max-line-length: 120
uses:
  - django
autodetect: true
requirements:
  - requirements.txt
ignore-paths:
  - docs
  - docker
ignore-patterns:
  - (^|/)docs(/|$)
python-targets:
  - 2
pep8:
  full: true