os:
    linux

language:
    python

python:
    - "2.7"

env:
    - TOX_ENV=django-1.10

before_install:
    - sudo apt-get update -y
    - sudo apt-get install postgresql libev libev-dev -y
    - psql -c "CREATE DATABASE SSMS_DB;"
    - psql -c "CREATE USER SSMS_USER WITH PASSWORD 'SSMS_PASS';"
    - psql -c "GRANT ALL PRIVILEGES ON DATABASE SSMS_DB TO SSMS_USER;"

install:
    - pip install tox tox-travis

script:
    - tox -e $TOX_ENV

after_success:
    - codecov --token=2bed3653-d88a-44e3-b1b1-4a81f79ae48e