language: python

python:
    - "2.7"

env:
   - TOX_ENV=django-1.10

install:
    - pip install tox tox-travis

script:
    - tox -e $TOX_ENV

after_success:
    - codecov --token=2bed3653-d88a-44e3-b1b1-4a81f79ae48e