os:
    linux

language:
    python

python:
    - "2.7"

services:
  - postgresql

env:
    - TOX_ENV=django-1.10

before_install:
    - sudo apt-get update -y
    - sudo apt-get install libev-dev -y

install:
    - pip install tox tox-travis

before_script:
  - psql -c "CREATE DATABASE SSMS_DB;" -U postgres
  - psql -c "CREATE USER SSMS_USER WITH PASSWORD 'SSMS_PASS';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE SSMS_DB TO SSMS_USER;" -U postgres

script:
    - tox -e $TOX_ENV

after_success:
    - codecov --token=2bed3653-d88a-44e3-b1b1-4a81f79ae48e