os:
    linux

language:
    python

python:
    - "2.7"

services:
  - postgresql

env:
    - TOX_ENV=django-1.10

before_install:
    - sudo apt-get update -y
    - sudo apt-get install libev-dev -y

install:
    - pip install tox tox-travis codecov

before_script:
  - psql -U postgres -c "create database TESTS;"

script:
    - tox -e $TOX_ENV

after_success:
    - codecov --token=2bed3653-d88a-44e3-b1b1-4a81f79ae48e