# define base image
FROM centos:7

# install dependent libraries
RUN yum install epel-release -y
RUN yum clean all
RUN yum groupinstall "Development Tools" -y
RUN yum install python-pip -y
RUN yum install python-devel postgresql-devel -y
RUN yum install libev libev-devel -y

# define volumes
VOLUME /ssms
