version: '2'
services:
  web:
    volumes:
      - ./ssms:/ssms
    ports:
      - '8000:8000'
    links:
      - postgres
    build:
      context: ../
      dockerfile: ./docker/web.dockerfile
  postgres:
    image: 'postgres:9'
